apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: igw-external-asm-hpa
  namespace: asm-ingress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: igw-external-asm
  minReplicas: 3
  maxReplicas: 10