apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: false   
      name: istio-ingressgateway
    pilot:
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: istio
                    operator: In
                    values:
                    - pilot
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: istio
                  operator: In
                  values:
                  - pilot
              topologyKey: kubernetes.io/hostname
        hpaSpec:
          maxReplicas: 10
          minReplicas: 2
        nodeSelector: 
          istio-nodepool: "true"
        podAnnotations:          
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        podDisruptionBudget:
          minAvailable: 1
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 512Mi
        tolerations:
        - effect: NoSchedule
          key: istio
          operator: Equal
          value: "true"
  # hub: gcr.io/istio-release  # Removing as we will use ASM images
  meshConfig:
    accessLogEncoding: JSON                                 
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      terminationDrainDuration: 50s
      tracing:
        sampling: 100
    enableTracing: true
  values:
    global:
      defaultNodeSelector:
        istio-nodepool: "true"
      defaultTolerations:
      - effect: NoSchedule
        key: istio
        operator: Equal
        value: "true"