apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: asm-ingressgateway-meshca-hpa
  namespace: asm-ingress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asm-ingressgateway-meshca #
  minReplicas: 3
  maxReplicas: 10