apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"istio-controlplane","namespace":"istio-system"},"spec":{"components":{"ingressGateways":[{"enabled":false,"name":"istio-ingressgateway"}],"pilot":{"k8s":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"istio","operator":"In","values":["pilot"]}]},"topologyKey":"failure-domain.beta.kubernetes.io/zone"},"weight":100}],"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"istio","operator":"In","values":["pilot"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"hpaSpec":{"maxReplicas":10,"minReplicas":2},"nodeSelector":{"istio-nodepool":"true"},"overlays":[{"kind":"Deployment","name":"istiod","patches":[{"path":"spec.template.spec.hostAliases","value":[{"hostnames":["login.uat.foo-corp.com"],"ip":"10.10.10.10"}]}]}],"podAnnotations":{"apm.datadoghq.com/env":"{ \"DD_ENV\": \"nonprod\", \"DD_TRACE_ANALYTICS_ENABLED\": \"true\" }","cluster-autoscaler.kubernetes.io/safe-to-evict":"true"},"podDisruptionBudget":{"minAvailable":1},"resources":{"limits":{"cpu":"4","memory":"4Gi"},"requests":{"cpu":"1000m","memory":"512Mi"}},"tolerations":[{"effect":"NoSchedule","key":"istio","operator":"Equal","value":"true"}]}}},"hub":"gcr.io/istio-release","meshConfig":{"accessLogEncoding":"JSON","accessLogFile":"/dev/stdout","defaultConfig":{"holdApplicationUntilProxyStarts":true,"proxyMetadata":{"DD_TRACE_ANALYTICS_ENABLED":"true"},"terminationDrainDuration":"50s","tracing":{"sampling":100}},"enableAutoMtls":true,"enableTracing":true},"values":{"global":{"defaultNodeSelector":{"istio-nodepool":"true"},"defaultTolerations":[{"effect":"NoSchedule","key":"istio","operator":"Equal","value":"true"}]}}}}
  creationTimestamp: "2021-06-21T18:56:48Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 1
  name: istio-controlplane
  namespace: istio-system
  resourceVersion: "85061"
  selfLink: /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/istio-controlplane
  uid: 652ed193-aa57-4907-89e9-7dc7da99ec80
spec:
  components:
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
    pilot:
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: istio
                    operator: In
                    values:
                    - pilot
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: istio
                  operator: In
                  values:
                  - pilot
              topologyKey: kubernetes.io/hostname
        hpaSpec:
          maxReplicas: 10
          minReplicas: 2
        nodeSelector:
          istio-nodepool: "true"
        overlays:
        - kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.hostAliases
            value:
            - hostnames:
              - login.uat.foo-corp.com
              ip: 10.10.10.10
        podAnnotations:
          apm.datadoghq.com/env: '{ "DD_ENV": "nonprod", "DD_TRACE_ANALYTICS_ENABLED":
            "true" }'
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        podDisruptionBudget:
          minAvailable: 1
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 512Mi
        tolerations:
        - effect: NoSchedule
          key: istio
          operator: Equal
          value: "true"
  hub: gcr.io/istio-release
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        DD_TRACE_ANALYTICS_ENABLED: "true"
      terminationDrainDuration: 50s
      tracing:
        sampling: 100
    enableAutoMtls: true
    enableTracing: true
  values:
    global:
      defaultNodeSelector:
        istio-nodepool: "true"
      defaultTolerations:
      - effect: NoSchedule
        key: istio
        operator: Equal
        value: "true"
status:
  componentStatus:
    Base:
      status: HEALTHY
    Pilot:
      status: HEALTHY
  status: HEALTHY
