apiVersion: v1
kind: Service
metadata:
  name: istio-igw-external
  namespace: istio-system
  labels:
    gateway: ingress-gateway
spec:
  type: LoadBalancer
  selector:
    gateway: ingress-gateway
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  - port: 15021
    targetPort: 15021
    name: status-port