apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    istio: ingressgateway
spec:
  type: LoadBalancer
  selector:
    istio: ingressgateway
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  - port: 15021
    targetPort: 15021
    name: status-port