apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: istio-igw-external-hpa
  namespace: istio-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway
  minReplicas: 3
  maxReplicas: 10