apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:  
  selector:
    matchLabels:
      gateway: ingress-gateway
  template:
    metadata:
      annotations:
        # Select the gateway injection template (rather than the default sidecar template)
        inject.istio.io/templates: gateway
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true" #due to known issue?      
      labels:
        # Set a unique label for the gateway. This is required to ensure Gateways can select this workload
        gateway: ingress-gateway
        # Enable gateway injection. If connecting to a revisioned control plane, replace with "istio.io/rev: revision-name"
        sidecar.istio.io/inject: "true"  
        istio.io/rev: default
    spec:
      affinity: 
        podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: gateway
                      operator: In
                      values:
                      - istio-igw-external
                  topologyKey: failure-domain.beta.kubernetes.io/zone
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: istio
                    operator: In
                    values:
                    - pilot
                topologyKey: kubernetes.io/hostname
      containers:
      - name: istio-proxy
        image: auto # The image will automatically update each time the pod starts.
        resources:
          requests:
            cpu: "2"
            memory: 512Mi
          limits:
            cpu: "4"
            memory: 1Gi 
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 3
      nodeSelector: 
          istio-nodepool: "true"
      tolerations:
      - effect: NoSchedule
        key: istio
        operator: Equal
        value: "true"
      
     
        
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-igw-external-sds
  namespace: istio-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-igw-external-sds
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-igw-external-sds
subjects:
- kind: ServiceAccount
  name: default