apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        label:
          istio: ingressgateway
        k8s:
          podAnnotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          hpaSpec:
            maxReplicas: 10
            minReplicas: 3
          resources:
            requests:
              cpu: "2"
              memory: 512Mi
            limits:
              cpu: "4"
              memory: 1Gi
          podDisruptionBudget:
            minAvailable: 2        
          readinessProbe:
            initialDelaySeconds: 10
            successThreshold: 3
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: istio
                      operator: In
                      values:
                      - istio-ingressgateway
                  topologyKey: failure-domain.beta.kubernetes.io/zone
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: istio
                    operator: In
                    values:
                    - istio-ingressgateway
                topologyKey: kubernetes.io/hostname
          service:
            ports:
            - port: 443
              name: https
              targetPort: 8443
            - port: 80
              name: http2
              targetPort: 8080
    pilot:
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: istio
                    operator: In
                    values:
                    - pilot
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: istio
                  operator: In
                  values:
                  - pilot
              topologyKey: kubernetes.io/hostname
        hpaSpec:
          maxReplicas: 10
          minReplicas: 2
        nodeSelector: 
          istio-nodepool: "true"
        podAnnotations:          
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        podDisruptionBudget:
          minAvailable: 1
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 512Mi
        tolerations:
        - effect: NoSchedule
          key: istio
          operator: Equal
          value: "true"
  hub: gcr.io/istio-release
  meshConfig:
    accessLogEncoding: JSON                                 
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      terminationDrainDuration: 50s
      tracing:
        sampling: 100
    enableTracing: true
  values:
    global:
      defaultNodeSelector:
        istio-nodepool: "true"
      defaultTolerations:
      - effect: NoSchedule
        key: istio
        operator: Equal
        value: "true"